apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployconversaotemp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: conversaotemp
  template:
    metadata:
      labels:
        app: conversaotemp
    spec:
      containers:
        - name: conversaotemp
          image: rodrigordavila/conversao-temperatura:latest
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  selector:
    app: conversaotemp
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort